### ISSUE TITLE
SHA1 no longer safe

### ISSUE THREAD

**Issue by GIVENALITY** [Repox/SimpleUsers#9]
Hello. Thank you for a great script. I wanted to ask how one can update the ecryption from SHA1 to a more advanced one in this script. That's really the major concern with the code.

**Comment by xuefengedu** [comment]
3 places:
1. https://github.com/Repox/SimpleUsers/blob/a7ba95732df50eaeef7619008945782164f20c47/simpleusers/users.obj.php#L57

2. https://github.com/Repox/SimpleUsers/blob/a7ba95732df50eaeef7619008945782164f20c47/simpleusers/users.obj.php#L81

3. https://github.com/Repox/SimpleUsers/blob/a7ba95732df50eaeef7619008945782164f20c47/simpleusers/users.obj.php#L286

**Comment by GIVENALITY** [comment]
> 3 places:
> 
> 1. [SimpleUsers/simpleusers/users.obj.php](https://github.com/Repox/SimpleUsers/blob/a7ba95732df50eaeef7619008945782164f20c47/simpleusers/users.obj.php#L57)
>        
>        
>             Line 57
>          in
>          [a7ba957](/Repox/SimpleUsers/commit/a7ba95732df50eaeef7619008945782164f20c47)
>        
>        
>        
>        
>    
>            
>              
>               			$sql = "INSERT INTO users VALUES (NULL, ?, SHA1(?), ?, NOW(), NOW())";
> 2. [SimpleUsers/simpleusers/users.obj.php](https://github.com/Repox/SimpleUsers/blob/a7ba95732df50eaeef7619008945782164f20c47/simpleusers/users.obj.php#L81)
>        
>        
>             Line 81
>          in
>          [a7ba957](/Repox/SimpleUsers/commit/a7ba95732df50eaeef7619008945782164f20c47)
>        
>        
>        
>        
>    
>            
>              
>               			$sql = "SELECT userId FROM users WHERE uUsername=? AND SHA1(CONCAT(uSalt, ?))=uPassword LIMIT 1";
> 3. [SimpleUsers/simpleusers/users.obj.php](https://github.com/Repox/SimpleUsers/blob/a7ba95732df50eaeef7619008945782164f20c47/simpleusers/users.obj.php#L286)
>        
>        
>             Line 286
>          in
>          [a7ba957](/Repox/SimpleUsers/commit/a7ba95732df50eaeef7619008945782164f20c47)
>        
>        
>        
>        
>    
>            
>              
>               			$sql = "UPDATE users SET uPassword=SHA1(?), uSalt=? WHERE userId=? LIMIT 1";

Thank you, @xuefengedu. This is useful. The challenge is I'm pretty shallow on hashing, can you show me how I implement SHA2 in those 3 lines?

**Comment by Repox** [comment]
I've made an update to use a more modern solution.
